"""Hand-built signal-bar series for the BTB-v2 E2 tests (roadmap V6).

The same series are embedded in MQL5/Scripts/ProBTB/BTB_Tests.mq5 (generated by
tools/gen_e2_fixtures.py), so both implementations are checked on identical bars.

OWNER is the owner's annotated chart as a synthetic M5 long:
  bars  0-15  warm-up (ATR14 becomes ready at bar 13)
  bars 16-18  decline into the leg-1 low L0 (bar 18)
  bar  19     breakout candle (the EVENT): zone 1995.70-1996.70, P = 1996.60
  bars 20-22  leg 1 up to H1 (bar 22)
  bar  23     pullback L1 (above the zone), bars 24-26 leg 2 to H2
  bar  27     pullback L2, bars 28-30 leg 3 to H3 (bar 30)
  bar  31     spike: 3.4 below H3 (>= 2 x ATR14 of bar 30)
  bars 32-39  push 1 (spike low, bar 31), bounce (fractal high, bar 34), push 2 (bar 37)
  bars 40-41  third push along the descending trend line into P: live from bar 40, P reached at bar 41
  bars 42-43  continuation up
"""

import calendar

T0 = calendar.timegm((2026, 1, 7, 2, 0, 0))     # Wednesday 02:00 broker time
PERIOD = 300
EVENT_BAR = 19


def _build(steps, start=2000.0, wick=0.1):
    out = []
    c = start
    for s in steps:
        o = c
        c = round(o + s, 2)
        out.append((o, round(max(o, c) + wick, 2), round(min(o, c) - wick, 2), c))
    return out


_WARM = [0.6, -0.9, 0.5, -0.8, 0.7, -0.6, 0.4, -0.9, 0.8, -0.5, 0.6, -0.7, 0.5, -0.8, 0.6, -0.7]
_LEGS = _build(_WARM + [-1.0] * 3 + [0.8] * 4 + [-1.6] + [0.8] * 3 + [-1.6] + [0.8] * 3)   # bars 0-30

OWNER = _LEGS + [
    (2000.6, 2000.7, 1997.3, 1997.4),     # 31 spike
    (1997.4, 1997.9, 1997.35, 1997.8),    # 32
    (1997.8, 1998.3, 1997.7, 1998.2),     # 33
    (1998.2, 1998.6, 1998.0, 1998.5),     # 34 fractal high between the pushes
    (1998.5, 1998.55, 1997.7, 1997.8),    # 35
    (1997.8, 1997.85, 1997.0, 1997.1),    # 36
    (1997.1, 1997.15, 1996.9, 1997.0),    # 37 push 2 (p2)
    (1997.0, 1997.5, 1996.95, 1997.4),    # 38
    (1997.4, 1997.7, 1997.3, 1997.6),     # 39 p2 confirmed
    (1997.6, 1997.65, 1997.2, 1997.3),    # 40 first live bar
    (1997.3, 1997.35, 1996.55, 1996.7),   # 41 third push reaches P
    (1996.7, 1997.6, 1996.65, 1997.5),    # 42
    (1997.5, 1998.4, 1997.4, 1998.3),     # 43
]

# STRUCTURE_FAILED: the first pullback L1 returns into the zone during the legs.
ZONE_TOUCH = _LEGS[:23] + [
    (1999.0, 1999.1, 1996.4, 1996.5),     # 23 pullback into the zone (low 1996.40 <= 1996.70)
    (1996.5, 1997.4, 1996.45, 1997.3),    # 24
    (1997.3, 1998.2, 1997.2, 1998.1),     # 25 confirms the pivot low of bar 23
    (1998.1, 1999.0, 1998.0, 1998.9),     # 26
]

# NO_SPIKE: after leg 3 a normal pullback (no 2 x ATR drop in 3 bars), then a lower high.
NO_SPIKE = _LEGS + [
    (2000.6, 2000.65, 1999.4, 1999.5),    # 31 pullback confirms H3
    (1999.5, 1999.6, 1998.8, 1998.9),     # 32 lowest low 1998.80 (spike needs <= 1998.60)
    (1998.9, 2000.0, 1998.85, 1999.9),    # 33
    (1999.9, 2000.3, 1999.8, 2000.2),     # 34 lower high than H3
    (2000.2, 2000.25, 1999.0, 1999.1),    # 35 confirms the lower high
    (1999.1, 1999.2, 1998.9, 1999.0),     # 36
]

# LINE_PASSED: the line reaches the breakeven but price stays above until the line passes the zone.
LINE_PASSED = OWNER[:40] + [
    (1997.6, 1997.65, 1997.2, 1997.3),    # 40
    (1997.3, 1997.6, 1997.25, 1997.5),    # 41
    (1997.5, 1997.55, 1997.1, 1997.2),    # 42
    (1997.2, 1997.6, 1997.15, 1997.5),    # 43
    (1997.5, 1997.55, 1997.1, 1997.2),    # 44
    (1997.2, 1997.6, 1997.15, 1997.5),    # 45
    (1997.5, 1997.55, 1997.1, 1997.2),    # 46
    (1997.2, 1997.6, 1997.15, 1997.5),    # 47
    (1997.5, 1997.55, 1997.1, 1997.2),    # 48
    (1997.2, 1997.6, 1997.15, 1997.5),    # 49
    (1997.5, 1997.55, 1997.1, 1997.2),    # 50
    (1997.2, 1997.6, 1997.15, 1997.5),    # 51
    (1997.5, 1997.55, 1997.1, 1997.2),    # 52
    (1997.2, 1997.6, 1997.15, 1997.5),    # 53
]

# EXPIRED_3_DAYS: same prices as LINE_PASSED, but bars 40.. fall on new broker dates.
EXPIRED = LINE_PASSED[:44]

# INVALIDATED_BEFORE_FILL: pushes 1.00 higher, so the line is still above P + tol when a crash bar
# goes through the whole zone.
INVALIDATED = OWNER[:31] + [
    (2000.6, 2000.7, 1998.3, 1998.4),     # 31 spike
    (1998.4, 1998.9, 1998.35, 1998.8),    # 32
    (1998.8, 1999.3, 1998.7, 1999.2),     # 33
    (1999.2, 1999.6, 1999.0, 1999.5),     # 34 fractal high
    (1999.5, 1999.55, 1998.7, 1998.8),    # 35
    (1998.8, 1998.85, 1998.0, 1998.1),    # 36
    (1998.1, 1998.15, 1997.9, 1998.0),    # 37 push 2
    (1998.0, 1998.5, 1997.95, 1998.4),    # 38
    (1998.4, 1998.7, 1998.3, 1998.6),     # 39 p2 confirmed
    (1998.6, 1998.65, 1995.6, 1995.8),    # 40 crash through the zone while the line is above P + tol
    (1995.8, 1996.0, 1995.5, 1995.9),     # 41
]


def times(n, day_breaks=None):
    """Bar open times: consecutive M5 bars; day_breaks = {bar index: whole days added from there on}."""
    out = []
    extra = 0
    for i in range(n):
        if day_breaks and i in day_breaks:
            extra = day_breaks[i]
        out.append(T0 + i * PERIOD + extra * 86400)
    return out


EXPIRED_DAYS = {40: 1, 41: 2, 42: 3, 43: 4}


def mirror(ohlc, m=4000.0):
    """Short mirror: price x -> m - x (highs and lows swap)."""
    return [(round(m - o, 2), round(m - l, 2), round(m - h, 2), round(m - c, 2)) for o, h, l, c in ohlc]
